[package]
name = "pcap-file"
edition = "2018"
version = "2.0.0-alpha1"
authors = ["Courvoif <courvoif@pm.me>"]
description = "A crate to read and write Pcap and PcapNg"

license = "MIT"
documentation = "https://docs.rs/pcap-file/"
repository = "https://github.com/courvoif/pcap-file"
readme = "README.md"
keywords = ["pcap", "pcapng", "parse", "read", "write"]
categories = ["encoding", "parsing"]

[dependencies]
byteorder = "1.3"
derive-into-owned = "0.1.0"
thiserror = "1.0"

[dev-dependencies]
glob = "0.3.0"